### ISSUE TITLE
Payment Methods not saving in Customer Groups

### ISSUE THREAD

**Issue by lonnyolson** [riconeitzel/PaymentFilter#10]
I installed the Payment Filter extension.  I am using magento version 1.7.0.1.  When I go to save the Payment Methods for a Customer Group they don't save. 

 I followed the instructions to run the following query: ALTER TABLE `customer_group` DROP `allowed_payment_methods`;

Not sure I should have done that now. It also says to remove old version of "cGroupPayments".  Is this an old table name.  Can't find this anywhere.

Thank you for your help.

**Comment by riconeitzel** [comment]
Hi,

sorry for no reply. I just didn't find a second time to go through the tickets :-( Did you solve your problem?

Rico

**Comment by riconeitzel** [comment]
See #14
