### ISSUE TITLE
Some weired issue after using this extension.

### ISSUE THREAD

**Issue by emobile-dev** [riconeitzel/PaymentFilter#13]
Hi guys,

I am using Magento 1.6.2 on my store. I have installed this extension from Magento Commerce page i.e. http://www.magentocommerce.com/magento-connect/paymentfilter-for-products-and-customer-groups.html
 
Installation was successful after changing magento connect installation method to Beta from stable. I have cleared all the caches and re logged in to the admin. I can see the extension in Sales -> Checkout page in Magneto Configuration. But while going to customer groups and click on any customer group I get some weired error. I have tried few methods to solve this but nothing worked. Following is the error : 
 
Mage registry key "_singleton/payfilter/observer" already exists
 
I Sincerely hope that some one can help me in this.

**Comment by riconeitzel** [comment]
Is there a filename and line given?

Best,
Rico

**Comment by emobile-dev** [comment]
Hi Rico,

Thanks for your replying. I have figured out the issue few minutes back. The issue was not related to the extension. I needed to disable the compilation mode in magento. And then it started working. 

I was testing the extension on my staging environment, i will now put it on my live site. Will post the result here.

And thank you very much for such a nice extension. 

Regards,

Gavin.
