### ISSUE TITLE
RicoNeitzel_PaymentFilter issue report and help request

### ISSUE THREAD

**Issue by vopija** [riconeitzel/PaymentFilter#14]
Hello,

I’m Vladimir and I’m working for Younify, we have client which is using your RicoNeitzel_PaymentFilter. We have issue which appears in admin we are not able to save changes in payment filter in Customer»»Customer groups, and outer issue appears when we are using payment filter to disable specify payment method in specify product in which case it disable all magento default payment methods. 
Magento ver. 1.8.0.0
RicoNeitzel_PaymentFilter Latest Version 0.1.6
If you have any additional questions please do not hesitate to contact me.
Looking forward to hearing from you.

**Comment by riconeitzel** [comment]
hi vladimir,

sorry for no reply. I just didn't find a second time to go through the tickets :-( Did you solve your problem?

Rico
