### ISSUE TITLE
Issue after installation and creating a dummy product

### ISSUE THREAD

**Issue by sudheerpal** [riconeitzel/PaymentFilter#16]
Hi till installation everything was fine. But as soon as i published a sample product with restricted payment method, there was a serious issue on magento website.

I am pasting error log-

a:5:{i:0;s:73:"Invalid backend model specified: payfilter/entity_backend_payment_methods";i:1;s:5858:"#0 /chroot/home/amarchit/deploy/releases/20150223100729/app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(346): Mage::exception('Mage_Eav', 'Invalid backend...')

Please suggest, how to resolve it.

**Comment by riconeitzel** [comment]
If you use compiler please recompile the compiler cache.

**Comment by sudheerpal** [comment]
Hi i did that,

Even i have removed the extension, then also i am getting same error.

Please refer this category URL   http://www.amarchitrakatha.com/in/magazines/national-geographic/natgeo-magazine
