### ISSUE TITLE
Methods not saving!

### ISSUE THREAD

**Issue by scudsy87** [riconeitzel/PaymentFilter#17]
Hey, I've just installed your extension on v1.8.0.1 and when I make the selections within the customer groups page, click save and it doesn't save the selection - there is also no error. Do you have any idea on what is causing this and how to fix it? Thanks in advance

**Comment by riconeitzel** [comment]
Hi Luke,

I’ve heard about that a few times but was never able to reproduce it … So I don’t know how to help you with that :(

Perhaps you can make a full dump of your store (anonymize customer data!) and give that to me?

Thanks
 Rico
