### ISSUE TITLE
Magento 1.9.1.0 issue at product page in admin

### ISSUE THREAD

**Issue by emobile-dev** [riconeitzel/PaymentFilter#18]
Hi There,

I have been planning to migrate my magento store from 1.6 to 1.9.1.0. I can see the option in configuration -> sales -> checkout. I have disabled all the payment methods except COD and Net Banking. Still I am seeing all the payment methods on the product page. Even its showing paypal though it is disabled from the Advanced Menu. Can you please help me to fix this issue.

Regards,

Gavin

**Comment by riconeitzel** [comment]
It must have been some caching issue then.
