### ISSUE TITLE
Magento 1.7.0.2 doesn't render select box on customer group edit page

### ISSUE THREAD

**Issue by hadizahedi** [riconeitzel/PaymentFilter#2]
First of all thanks for your great extension you worked on.

I'm using Magento 1.7.0.2 and after installing Payment Filter through Magento Connect, Unfortunately No Select box show up under every Customer Group.
But there is this setting in every product's price page which I can disable one of my payment methods. If I disable some of them, it takes NO effect in checkout page.

Would you please help me solve any possible reasons.
Website Address: dressupwithstyle.com
![pf2](https://f.cloud.github.com/assets/4710603/659262/282e994a-d679-11e2-8975-f64bd1a94895.png)
![pf1](https://f.cloud.github.com/assets/4710603/659261/275c0250-d679-11e2-899e-dfbab0a2546e.png)
![pf3](https://f.cloud.github.com/assets/4710603/659263/28751e60-d679-11e2-9e47-1fa91210390d.png)

**Comment by dotbill** [comment]
It's an old issue - however this is most likely down to another module rewriting the customer group edit form. If this comes up with anyone else:

- Find the other module that is rewriting adminhtml module customer_group_edit_form
- Chain this module off the existing one, ie:

`class RicoNeitzel_PaymentFilter_Block_Adminhtml_Group_Form extends EXISTINGMODULE_Block_Adminhtml_Customer_Group_Edit_Form
`
- Make this module depend on the existing one (Add another entry to <depends> in app/etc/modules/RicoNeitzel_PaymentFilter.xml)

A quick google shows other people having issues with multiple modules rewriting the same class and other ways of dealing with it.

I can provide more verbose detail if needed!

**Comment by riconeitzel** [comment]
👍 thanks @dotbill
