### ISSUE TITLE
Adding Payment Method option which isn't listed

### ISSUE THREAD

**Issue by ne0nlight** [riconeitzel/PaymentFilter#23]
I am working on implementing your extension to help customize my webstore, however I have a quick question. We have implemented an extension for one of our payment methods which enables us to use our payment services provider which is not one of the default options by Magento, nor is it one of the many listed options that comes with your extension outside of the defaults. (http://www.estesolutions.com/index.php/magento-extension/quickbooks-merchant-services-hosted-paypage/)

So my question would be that if it possible and how would I do it if it is, that I can add QBMS to the list of options to be selected for a groups payment option, and would it be as simple as that as it is a hosted paypage much like a jumping to a paypal hosted page works. Thanks for your help!

**Comment by riconeitzel** [comment]
See #24
