### ISSUE TITLE
Uninstalling Extension

### ISSUE THREAD

**Issue by ne0nlight** [riconeitzel/PaymentFilter#25]
Hello,

I am trying to temporarily uninstall the extension, and have removed all associated files, and ran the SQL dump listed in the Readme, however page is still broken giving the error:

    Error:
    Invalid backend model specified: payfilter/entity_backend_payment_methods

    Trace:
    #0 /app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(346): Mage::exception('Mage_Eav', 'Invalid backend...')
    #1 /app/code/core/Mage/Eav/Model/Entity/Abstract.php(1094): Mage_Eav_Model_Entity_Attribute_Abstract->getBackend()
    #2 /app/code/core/Mage/Eav/Model/Entity/Abstract.php(998): Mage_Eav_Model_Entity_Abstract->_setAttributeValue(Object(Mage_Customer_Model_Customer), Array)
    #3 /app/code/core/Mage/Eav/Model/Entity/Abstract.php(959): Mage_Eav_Model_Entity_Abstract->_loadModelAttributes(Object(Mage_Customer_Model_Customer))
    #4 /app/code/core/Mage/Core/Model/Abstract.php(225): Mage_Eav_Model_Entity_Abstract->load(Object(Mage_Customer_Model_Customer), '141', NULL)
    #5 /app/code/core/Mage/Customer/Model/Session.php(116): Mage_Core_Model_Abstract->load('141')
    #6 /app/code/core/Mage/Checkout/Controller/Action.php(43): Mage_Customer_Model_Session->getCustomer()
    #7 /app/code/core/Mage/Checkout/controllers/OnepageController.php(60): Mage_Checkout_Controller_Action->_preDispatchValidateCustomer()
    #8 /app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Checkout_OnepageController->preDispatch()
    #9 /app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
    #10 /app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
    #11 /app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
    #12 /app/Mage.php(684): Mage_Core_Model_App->run(Array)
    #13 /index.php(87): Mage::run('', 'store')
    #14 {main}

Any ideas? Thanks

**Comment by riconeitzel** [comment]
Make sure to clear caches, reindex and rerun compiler.

Best,
Rico

**Comment by ne0nlight** [comment]
I've done all that, and still throws the same error.

One thing to note, I don't think I noticed any of the tables to drop before even implementing the SQL, any ideas what it could be if anything other than that?

Exact thing I've done is gone and deleted all files which are installed from app/ and on. Then the SQL. Not sure what else could be done!

**Comment by riconeitzel** [comment]
Delete the line from eav_attribute where backend_model is payfilter/entity_backend_payment_methods

Rico

**Comment by keshavpatidar1988** [comment]
Thanks it worked.
