### ISSUE TITLE
Payment method not appearing on checkout

### ISSUE THREAD

**Issue by tnouland** [riconeitzel/PaymentFilter#29]
The 'Check / Money Order' payment method is not showing up for the customer group to which we've assigned this method when checking out. Even when directly assigning the payment method to a user, it won't show up on checkout. Other payment methods work just fine.

The Magento version is 1.9.10 and the module has been updated to the latest version available. Do you have any thoughts on the cause or how to fix this?

**Comment by riconeitzel** [comment]
Can you see https://github.com/riconeitzel/PaymentFilter/issues/24#issuecomment-254730177 please and check if that helps? I haven't tested it yet.
