### ISSUE TITLE
Module not working with Express checkout of paypal

### ISSUE THREAD

**Issue by SrikanthThandra** [riconeitzel/PaymentFilter#3]
Hi,

  I am using paypal express check out and when I login to the admin go to customer->Manage Customer Group and selected not login user there I have the option of paypal express checkout which I selected it. Now the express checkout button appears on product page and cart page. But in checkout page when I go to payment page I don't see paypal there. May be because what comes in checkout page is paypal stander. I hope I am clear can you please fix this issue.

Thanks & Regards,
Srikanth Thandra

**Comment by riconeitzel** [comment]
See #14
