### ISSUE TITLE
Crash upon installing - duplicate?

### ISSUE THREAD

**Issue by srmobile** [riconeitzel/PaymentFilter#30]
Hi,

Running on Magento 1.9.2.4, I would really love to get this going but as soon as it is dropped in, it crashes my site. I checked and there is no other attribute with this name so I have no idea why it is saying there is.

Crash report:

> Error in file: "/home/site/public_html/app/code/community/RicoNeitzel/PaymentFilter/sql/payfilter_setup/mysql4-install-0.1.0.php" - SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'allowed_payment_methods'

Trace:
#0 /home/site/public_html/app/code/core/Mage/Core/Model/Resource/Setup.php(644): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /home/site/public_html/app/code/core/Mage/Core/Model/Resource/Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb('install', '', '1.0.0')
#2 /home/site/public_html/app/code/core/Mage/Core/Model/Resource/Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('1.0.0')
#3 /home/site/public_html/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /home/site/public_html/app/code/core/Mage/Core/Model/App.php(428): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /home/site/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Model_App->_initModules()
#6 /home/site/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#7 /home/site/public_html/index.php(83): Mage::run('', 'store')
#8 {main}

Thanks

SR

**Comment by riconeitzel** [comment]
Hi,

was it installed before? Did the installation failed a first time?

This error is caused by an already upgraded customer_group table.

Remove the column 'allowed_payment_methods' from the customer_group table and access the backend!

Rico

**Comment by srmobile** [comment]
Hi Rico,
Thanks for the quick reply!

To be honest it is entirely possible that I installed this at one point, but I do not remember. The column "'allowed_payment_methods" is present only when I drop in the files. 

Once I drop the files in, the site crashes, the column appears. I delete the column, I can now access the site but I cannot save any payment method for customer groups. I select, save and when I go back it is de-selected.

Any thoughts?

Thank you!

SR

**Comment by riconeitzel** [comment]
Usually, the install scripts should run again after deleting the columns … so I can not reproduce the behaviour you describe :-( without looking into the system.

If you need support and let me install that you could contact my company at info@buro71a.de - we (or I) can assist you and do the installation for you.

**Comment by srmobile** [comment]
Is it possible that this is because I'm using MariaDB 10?

**Comment by riconeitzel** [comment]
I don't think so as it's a drop-in replacement.
