### ISSUE TITLE
Logging in a file "5"

### ISSUE THREAD

**Issue by schmengler** [riconeitzel/PaymentFilter#32]
The extensions logs debug messages to `var/log/5`

>  RicoNeitzel_PaymentFilter_Helper_Data: Loading quote from session. If this line floods the logs we are in _afterLoad of a cart being loaded. See: https://github.com/riconeitzel/PaymentFilter/issues/19

`5` happens to be `Zend_Log::NOTICE`, so the parameters here are wrong:
https://github.com/riconeitzel/PaymentFilter/blob/master/app/code/community/RicoNeitzel/PaymentFilter/Helper/Data.php#L181-L187

**Comment by riconeitzel** [comment]
Fixed in 353436cb24548d5bcc63f166879227cffe145da6 – does this work for you? :-)

**Comment by schmengler** [comment]
Woah, you are fast. I was about to create a PR, but I'll take that too. Thanks :)
