### ISSUE TITLE
Out of memory errors loading the site

### ISSUE THREAD

**Issue by obfus-cutor** [riconeitzel/PaymentFilter#6]
Hi!

I had an issue with a site loading, and i believe it is related to a plugin. It was pretty tricky and sporadic, but i was able to trace it down. An issue occurred with a user navigating a site for the first time, having been logged in before. This is very similar to  
http://www.magentocommerce.com/boards/viewthread/38843/P30/#t401914

> So somewhere in the execution of the the line using the helper it ran into problems. 
> The weird part is that it was only on a users first visit to the site, or more accurately, 
> a user that had no cookies from the site. If I deleted my cookies I could recreate the 
> error every time. But once I had run into the error and refreshed the page, everything 
> worked fine, no conflicts no errors. 

and there is two places that may be affected by this issue in 
app\code\community\RicoNeitzel\PaymentFilter\Helper\Data.php

getForbiddenPaymentMethodsForCart() - line 65
> $items = Mage::getSingleton('checkout/cart')->getQuote()->getAllItems();
and
loadProductPaymentMethodsOnCartItemProducts() - line 176
> foreach (Mage::getSingleton('checkout/cart')->getQuote()->getAllItems() as $item) {

to be frank, i didn't go too far and just commented those functions, since we are not using per product based payment filters.

And a post, mentioned above,  suggests to replace
 $items = Mage::helper('checkout/cart')->getCart()->getItems()->getData(); 
to
 $items = Mage::getSingleton('checkout/session')->getQuote()->getAllItems();

**Comment by riconeitzel** [comment]
This might be addressed by #19
