### ISSUE TITLE
No stable / tag for install by composer

### ISSUE THREAD

**Issue by ProxiBlue** [riconeitzel/PaymentFilter#8]
Please can you tag a release for composer install

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package riconeitzel/payment-filter could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by avstudnitz** [comment]
+1

**Comment by riconeitzel** [comment]
1.1.0 tagged ✅
